# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Sanity QAX Patient

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print Chrome version
      run: /usr/bin/google-chrome --version
    - name: Print Chromium version
      run: /usr/bin/chromium --version
    - name: Print ChromeDriver version
      run: /usr/bin/chromedriver --version
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn clean test -DsuiteFile=smokeTests_PrimaryCare_Patient_Org_QAX.xml -Denvironment=hlthbcqax_patient_org -Dtest_rail=no
      run: mvn clean test -DsuiteFile=sanity_Primary_Care_QAX.xml -Denvironment=hlthbcqax_patient_org -Dtest_rail=no
      #mvn clean test -DsuiteFile=smokeTests_PrimaryCare_Provider_Org_QAX.xml -Denvironment=hlthbcqax_provider_org -Dtest_rail=no
