name: Chromium Version Issue

on:
  push:

jobs:
  print-chrome-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Chrome version
        run: /usr/bin/google-chrome --version
      - name: Print Chromium version
        run: /usr/bin/chromium --version
      - name: Print ChromeDriver version
        run: /usr/bin/chromedriver --version
